# Generated by Django 2.2.4 on 2019-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20191012_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='english',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='japanese',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='math',
            field=models.IntegerField(),
        ),
    ]
