# Generated by Django 2.2.6 on 2019-10-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_reportproblem_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='teacher',
            new_name='is_teacher',
        ),
    ]
