# Generated by Django 2.2.6 on 2019-10-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_auto_20191015_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.ReportProblem'),
        ),
    ]
