# Generated by Django 2.2.6 on 2019-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
